[View in Colaboratory](https://colab.research.google.com/github/cjimti/learning-pytorch/blob/master/01_notes.ipynb)

---
published: true
layout: post
title: Essential PyTorch
tags: coding python
featured: coding python
mast: torch
---

The Facebook AI Research team released [PyTorch], "a deep learning framework for fast, flexible experimentation." as an open source project in early 2017. [PyTorch] has gained rapid adoption by the deep learning community for building neural networks in Python, and working seamlessly with [numpy], [PyTorch] could even be used as a [numpy] replacement.


### Install

Install using [Anaconda]:

```bash
conda install pytorch torchvision -c pytorch
```

### Tensors

[PyTorch] allows you to build neural networks using tensors. Tensors in [PyTorch] are easlity converted to and from nsarrays in [numpy]. So, if you have worked with [numpy] you have worked with [PyTorch] tensors.



[PyTorch]: https://pytorch.org/
[numpy]: https://mk.imti.co/python-data-essentials-numpy/
[tensor]: https://en.wikipedia.org/wiki/Tensor
[Anaconda]: https://conda.io/docs/user-guide/install/download.html

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

%matplotlib inline

# http://pytorch.org/
!pip3 install torch torchvision
import torch

a = [[1,2], [3,4]]
print(a)

np.array(a)

    100% |████████████████████████████████| 484.0MB 28kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5c760000 @  0x7f043cbec1c4 0x46d6a4 0x5fcbcc 0x4c494d 0x54f3c4 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54e4c8
    100% |████████████████████████████████| 61kB 9.4MB/s 
    100% |████████████████████████████████| 2.0MB 1.9MB/s 


  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0
[[1, 2], [3, 4]]


array([[1, 2],
       [3, 4]])

In [2]:
torch.Tensor(a)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

In [3]:
tensor_cpu = torch.ones(2,2)

# move to GPU if available (CPU is default)
if torch.cuda.is_available():
  print("GPU is available.")
  tensor_cpu.cuda()
    
tensor_cpu.cuda()

GPU is available.


tensor([[ 1.,  1.],
        [ 1.,  1.]], device='cuda:0')